
esphome:
  name: esphome-web-436bc0
  friendly_name: ESPHome Web 436bc0 (ESP32)
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# sensor:
#   - platform: internal_temperature
#     accuracy_decimals: 1
#     name: "Internal Temp"

#bluetooth_proxy:
#  active: True

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms

#esp32_ble_beacon:
#  type: iBeacon
#  uuid: '57435d29-bdac-1984-e85f-42bcd17556c6'

# Git repo examples https://esphome.io/components/packages
#packages:
  # shorthand form github://username/repository/[folder/]file-path.yml[@branch-or-tag]
  #remote_package_shorthand: github://esphome/non-existant-repo/file1.yml@main

  #remote_package_files:
  #  url: https://github.com/petrix-h/waveshare-esp32-s3-1.24-round
  #  files: [w-roundscreen.yaml]  # optional; if not specified, all files will be included
  #  ref: initial-screen-trials  # optional
  #  refresh: always  # optional

i2c:
  sda: GPIO05
  scl: GPIO18
  scan: true
  #id: bus_a

# packages:
#   remote_package_files:
#    url: https://github.com/petrix-h/esphome
#    files: [sensors/si7021.yaml]  # optional; if not specified, all files will be included
#    ref: main  # optional
#    refresh: always  # optional

# packages:
#   remote_package_files:
#    url: https://github.com/petrix-h/esphome
#    files: [sensors/GY-BMME_PM280.yaml]  # optional; if not specified, all files will be included
#    ref: main  # optional
#    refresh: always  # optional

# CJMCU-8128 Example configuration entry I2C
sensor:
  - platform: ccs811
    eco2:
      name: "CJMCU-8128 CCS811 eCO2 Value"
    tvoc:
      name: "CJMCU-8128 CCS811 Total Volatile Organic Compound"
    #address: 0x5A
    update_interval: 60s
    #baseline: 0xA483 # After 20-30 min, check esp logs for baseline=, needs recalib over time
    #temperature: cjmcu_temp # Optional, can improve readings
    #humidity: cjmcu_humid # Optional, can improve readings


  - platform: bmp280_i2c
    temperature:
      name: "CJMCU-8128 Outside Temperature"
      id: cjmcu_temp
      oversampling: 16x
    pressure:
      name: "CJMCU-8128 Outside Pressure"
    address: 0x76
    update_interval: 60s

  - platform: htu21d
    model: SI7021 #htu21d
    temperature:
      name: "CJMCU-8128 Temperature"
    humidity:
      name: "CJMCU-8128 Humidity"
      id: cjmcu_humid
    heater:
      name: "CJMCU-8128 Heater"
  #TODO enable heater: https://github.com/esphome/issues/issues/4975
  
  # Example configuration entry for abs humidity
  - platform: absolute_humidity
    name: "CJMCU-8128 Absolute Humidity"
    temperature: cjmcu_temp
    humidity: cjmcu_humid
    #equation: #(Optional): The saturated vapor pressure equation to use (see below).
  
#http://www.kevinahrendt.com/approximating-dew-points
  - platform: template
    name: "${upper_device_name} Dew Point"
    id: dewPoint
    update_interval: 60s
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1                                # formula is uncertain up to 0.35 degrees C = 0.63 degrees F for usual indoor temperatures
    lambda: |- 
        const float alpha = 6.112;                      // (hPa)
        const float beta = 17.62;
        const float lambda = 243.12;                    // (degrees C)

        float RH = id(cjmcu_humid).raw_state;              // Relative Humidity
        float T = id(cjmcu_temp).raw_state;            // Temperature in (degrees C)

        float H = log( RH/100 ) + beta*T/(lambda+T);
        return (lambda)*H/(beta - H);


