# CJMCU-8128 Example configuration entry I2C
sensor:
  - platform: ccs811
    eco2:
      name: "CJMCU-8128 CCS811 eCO2 Value"
    tvoc:
      name: "CJMCU-8128 CCS811 Total Volatile Organic Compound"
    #address: 0x5A
    update_interval: 60s
    #baseline: 0xA483 # After 20-30 min, check esp logs for baseline=, needs recalib over time
    #temperature: cjmcu_temp # Optional, can improve readings
    #humidity: cjmcu_humid # Optional, can improve readings


  - platform: bmp280_i2c
    temperature:
      name: "CJMCU-8128 Outside Temperature"
      id: cjmcu_temp
      oversampling: 16x
    pressure:
      name: "CJMCU-8128 Outside Pressure"
    address: 0x76
    update_interval: 60s

  - platform: htu21d #seems broken
    model: SI7021 #htu21d
    id: cjmcu_8188_si7021_with_heater
    temperature:
      name: "CJMCU-8128 Temperature"
      disabled_by_default: True
      entity_category: "diagnostic"
    humidity: #seems broken
      name: "CJMCU-8128 Humidity"
      id: cjmcu_humid
      #internal: True
      disabled_by_default: True
      entity_category: "diagnostic"
    heater:
      name: "CJMCU-8128 Heater"
      disabled_by_default: True
      entity_category: "diagnostic"

#Turn on the heater... https://github.com/esphome/issues/issues/4975
switch: #doesn't seem to work but the sensor itself also seems broken
  - platform: template
    name: "Garage Sensor Heater Switch"
    restore_mode: disabled
    disabled_by_default: True
    entity_category: "diagnostic"
    lambda: |-
      return id(cjmcu_8188_si7021_with_heater).is_heater_enabled();
    turn_on_action:
      - lambda: |-
            id(cjmcu_8188_si7021_with_heater).set_heater_level(4);
            id(cjmcu_8188_si7021_with_heater).set_heater(true);
    turn_off_action:
      - lambda: |-
            id(cjmcu_8188_si7021_with_heater).set_heater_level(0);
            id(cjmcu_8188_si7021_with_heater).set_heater(false);
