---
packages:
  remote_package_files:
    url: https://github.com/petrix-h/esphome
    files: 
      #- configs/debug.yaml
      - configs/internal-temp.yaml
      - configs/wifi-stats.yaml
      - voice-assistant/voice-assistant.yaml  # optional; if not specified, all files will be included
    ref: voice-assistant #main  # optional
    refresh: always  # optional

substitutions:
  #name: esp32-s3-box-3
  name: esp32-s3-voice-assistant
  friendly_name: ESP32 S3 Voice Assistant

psram:

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  #flash_size: 4MB
  framework:
    type: esp-idf

#Reduce power and heat
#esp32_ble:
#  enable_on_boot: false    

api:
  encryption:
     key: !secret tutorial-voice-assistant-encryption-key

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret tutorial-voice-assistant-ota-password

logger:
#  hardware_uart: USB_SERIAL_JTAG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.189.28
    gateway: 192.168.189.1
    subnet: 255.255.255.0

captive_portal:

